CREATE TABLE `users` (
    id INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    sha256 VARCHAR(128) NOT NULL,
    validator VARCHAR(64) NOT NULL,
    validation_time TIMESTAMP NOT NULL,
    salt VARCHAR(64) NOT NULL,
    admin TINYINT(1)
);

CREATE TABLE `rooms` (
    id INT PRIMARY KEY,
    name VARCHAR(256) NOT NULL,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creator INT NOT NULL,
    background_music BLOB,
    background_music_mime VARCHAR(64),
    background_image BLOB,
    background_image_mime VARCHAR(64),
    FOREIGN KEY (creator) REFERENCES users (id)
);

CREATE TABLE `message` (
    id INT PRIMARY KEY,
    content VARCHAR(1024) NOT NULL,
    tone VARCHAR(16),
    authorid INT NOT NULL,
    roomid INT NOT NULL,
    sent DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sound BLOB,
    mime VARCHAR(64),
    FOREIGN KEY (authorid) REFERENCES users (id),
    FOREIGN KEY (roomid) REFERENCES rooms (id)
);

CREATE TABLE `room_link` (
    roomid INT PRIMARY KEY,
    userid INT PRIMARY KEY,
    FOREIGN KEY (roomid) REFERENCES rooms (id),
    FOREIGN KEY (userid) REFERENCES users (id)
);

CREATE TABLE `user_mime_link` (
    userid INT NOT NULL,
    mime_default VARCHAR(64) NOT NULL,
    mime_j VARCHAR(64),
    mime_hj VARCHAR(64),
    mime_bj VARCHAR(64),
    mime_js VARCHAR(64),
    mime_s VARCHAR(64),
    mime_srs VARCHAR(64),
    mime_nsrs VARCHAR(64),
    mime_lh VARCHAR(64),
    mime_hlh VARCHAR(64),
    mime_gen VARCHAR(64),
    mime_i VARCHAR(64),
    mime_ui VARCHAR(64),
    mime_vu VARCHAR(64),
    mime_ij VARCHAR(64),
    mime_ref VARCHAR(64),
    mime_t VARCHAR(64),
    mime_nm VARCHAR(64),
    mime_lu VARCHAR(64),
    mime_nf VARCHAR(64),
    mime_nbh VARCHAR(64),
    mime_nsb VARCHAR(64),
    mime_nay VARCHAR(64),
    mime_ay VARCHAR(64),
    mime_nbr VARCHAR(64),
    mime_nv VARCHAR(64),
    mime_ot VARCHAR(64),
    mime_th VARCHAR(64),
    mime_cb VARCHAR(64),
    mime_f VARCHAR(64),
    mime_q VARCHAR(64),
    mime_lyr VARCHAR(64),
    mime_c VARCHAR(64),
    mime_m VARCHAR(64),
    mime_li VARCHAR(64),
    mime_rh VARCHAR(64),
    mime_hyp VARCHAR(64),
    mime_e VARCHAR(64),
    mime_ex VARCHAR(64),
    mime_p VARCHAR(64),
    mime_r VARCHAR(64),
    mime_a VARCHAR(64),
    mime_sx VARCHAR(64),
    mime_nsx VARCHAR(64),
    mime_ns VARCHAR(64),
    mime_pos VARCHAR(64),
    mime_neg VARCHAR(64),
    mime_neu VARCHAR(64),
    mime_nh VARCHAR(64),
    mime_npa VARCHAR(64),
    mime_st VARCHAR(64),
    mime_mj VARCHAR(64),
    mime_ma VARCHAR(64),
    mime_hsrs VARCHAR(64),
    mime_hs VARCHAR(64),
    mime_dr VARCHAR(64),
    mime_dkm VARCHAR(64),
    mime_cwh VARCHAR(64),
    mime_cr VARCHAR(64),
    mime_cur VARCHAR(64),
    mime_mhly VARCHAR(64),
    mime_msrs VARCHAR(64),
    mime_ms VARCHAR(64),
    mime_non VARCHAR(64),
    mime_genq VARCHAR(64),
    mime_jbt VARCHAR(64)
);

